In [ ]:
import pandas as pd
original = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/all_shops.csv')
df= original.copy()

In [ ]:
df

,item,url,artist,discount_price,price,is_sold_out,ds,vendor,is_autograph,avg_review_value,number_of_questions,number_of_reviews,presale
0,TWICE 11th MINI ALBUM BETWEEN 1&2,https://en.thejypshop.com/product/twice-11th-m...,TWICE,18.55,22.90,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
1,1st Mini Album IM NAYEON,https://en.thejypshop.com/product/1st-mini-alb...,NAYEON,17.82,22.00,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
2,TWICE 1st Mini Album The Story Begins,https://en.thejypshop.com/product/twice-1st-mi...,TWICE,11.91,14.70,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
3,TWICE 3rd Mini Album TWICEcoaster : LANE 1,https://en.thejypshop.com/product/twice-3rd-mi...,TWICE,12.64,15.60,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
4,Special Album TWICEcoaster : LANE 2,https://en.thejypshop.com/product/special-albu...,TWICE,14.09,17.40,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22783,"TETEMPEST - 1st Mini Album [It’s ME, It’s WE]",https://shop.mwave.me/en/565732.html,NaN,NaN,28.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22784,P1Harmony - 3rd Mini Album [DISHARMONY : FIND ...,https://shop.mwave.me/en/565642.html,NaN,NaN,26.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22785,fromis_9 – 4th Mini Album [Midnight Guest],https://shop.mwave.me/en/565599.html,NaN,NaN,27.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22786,BLITZERS - 1st Single [BOBBIN],https://shop.mwave.me/en/565506001.html,NaN,NaN,22.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22787,KIM JAEHWAN - 4th Mini Album [THE LETTER],https://shop.mwave.me/en/565465001.html,NaN,NaN,28.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN

In [ ]:
df.isna().sum()

item                       0
url                        0
artist                 22619
discount_price         17643
price                     78
is_sold_out               40
ds                         0
vendor                     0
is_autograph           10391
avg_review_value       11942
number_of_questions    11942
number_of_reviews      11942
presale                12566
dtype: int64

In [ ]:
df.shape

(22788, 13)

In [ ]:
df.describe()

,discount_price,price,avg_review_value,number_of_questions,number_of_reviews
count,5145.000000,22710.000000,10846.000000,10846.000000,10846.000000
mean,17.010383,27.281207,1.693079,0.000369,2.283976
std,10.421036,22.057108,2.347889,0.030364,12.747754
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,11.890000,14.990000,0.000000,0.000000,0.000000
50%,14.500000,20.990000,0.000000,0.000000,0.000000
75%,17.180000,31.930000,5.000000,0.000000,1.000000
max,113.610000,269.990000,5.000000,3.000000,772.000000

In [ ]:
df = df[df['price']<=80]

In [ ]:
df['artist'].replace('WONPIL(DAY6)','DAY6',inplace = True)
df['artist'].replace('Young K(DAY6)','DAY6',inplace = True)

/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [ ]:
df.reset_index(drop = True, inplace = True)

In [ ]:
def artist_na(value, inplace):
  index = df[(df['item'].str.contains(value))&(df['artist'].isna() == True)].index
  if inplace == '' :
    df.iloc[index,2] = value
  else :
    df.iloc[index,2] = inplace
  return

In [ ]:
artist_na('엔플라잉','')
artist_na('N.FLYING','엔플라잉')
artist_na('SUPER JUNIOR','')
artist_na('Super Junior','SUPER JUNIOR')
artist_na('슈퍼주니어','SUPER JUNIOR')
artist_na('Weki Meki','위키미키')
artist_na('WEKI MEKI','위키미키')
artist_na('위키미키','')
artist_na('MCND','')
artist_na('Golden Child','GOLDEN CHILD')
artist_na('GOLDEN CHILD','')
artist_na('P1Harmony','')
artist_na('피원하모니','P1Harmony')
artist_na('TETEMPEST','TEMPEST')
artist_na('TEMPEST','')
artist_na('fromis_9','Fromis_9')
artist_na('FROMIS_9','Fromis_9')
artist_na('Fromis_9','')
artist_na('BLITZERS','')
artist_na('KIM JAEHWAN','김재환')
artist_na('김재환','')
artist_na('TVXQ','')
artist_na('Han Seung Woo','한승우')
artist_na('한승우','')
artist_na('EXO','')
artist_na('NAYEON','')
artist_na('NA YEON','NAYEON')
artist_na('나연','NAYEON')
artist_na('GHOST9','')
artist_na('Ghost9','GHOST9')
artist_na('EPEX','')
artist_na('CHERRY BULLET','')
artist_na('Cherry Bullet','CHERRY BULLET')
artist_na('NCT 127','NCT 127')
artist_na('NCT127','')
artist_na('JUST B','')
artist_na('BIGBANG','')
artist_na('SHINEE','')
artist_na('Shinee','SHINEE')
artist_na('SHINee','SHINEE')
artist_na('샤이니','SHINEE')
artist_na('FTISLAND','')
artist_na('F.T. ISLAND','FTISLAND')
artist_na('D-Crunch','D-CRUNCH')
artist_na('D-CRUNCH','')
artist_na('RED VELVET','')
artist_na('Red Velvet','RED VELVET')
artist_na('Yoon Jisung','')
artist_na('WOODZ','')
artist_na('YOUNITE','')
artist_na("E'LAST",'')
artist_na('Woodz','WOODZ')
artist_na('DAY6','')
artist_na('Day6','DAY6')
artist_na('1THE9','')
artist_na('ASTRO','')
artist_na('JO YURI','조유리')
artist_na('조유리','')
artist_na('Kep1er','KEP1ER')
artist_na('KEP1ER','')
artist_na('woo!ah!','')
artist_na('LIGHTSUM','')
artist_na('BVNDIT','')
artist_na('Lovelyz','')
artist_na('러블리즈','Lovelyz')
artist_na('LOVELYZ','Lovelyz')
artist_na('B1A4','')
artist_na('Kim Woo Seok','김우석')
artist_na('김우석','')
artist_na('CHUNG HA','')
artist_na('Chungha','CHUNG HA')
artist_na('CHUNGHA','CHUNG HA')
artist_na('ATBO','')
artist_na('SF9','')
artist_na('TO1','')
artist_na('N.Flying','엔플라잉')
artist_na('SECHSKIES','젝스키스')
artist_na('젝스키스','')
artist_na('AleXa','')
artist_na('Layone','')
artist_na('CHOI YOOJUNG','')
artist_na('YENA','')
artist_na('CHOI YE NA','YENA')
artist_na('JEONG EUN JI','')
artist_na('TRADE L','')
artist_na('WONHO','')
artist_na('BLACKPINK','')
artist_na('BLACK PINK','BLACKPINK')
artist_na('Black Pink','BLACKPINK')
artist_na('Blackpink','BLACKPINK')
artist_na('BlackPink','BLACKPINK')
artist_na('j-hope','J-HOPE')
artist_na('J-HOPE','')
artist_na('NINE.i','')
artist_na('Xdinary Heroes','')
artist_na('IN2IT','')
artist_na('EVERGLOW','')
artist_na('SEVENTEEN','')
artist_na('Seventeen','SEVENTEEN')
artist_na('Acid Angel from Asia','tripleS')
artist_na('tripleS','')
artist_na('ONF','')
artist_na('WJSN','')
artist_na('MOMOLAND','')
artist_na('JUKJAE','')
artist_na('JOHN NOH & YEONG YEOL KO','')
artist_na('YONG JUN HYUNG','')
artist_na('VERIVERY','')
artist_na('VeriVery','VERIVERY')
artist_na('양요섭','')
artist_na('KIM JONG HYEON','김종현')
artist_na('김종현','')
artist_na('BADLAMB','')
artist_na('ENOi','')
artist_na('CIX','')
artist_na('Monsta X','MONSTA X')
artist_na('MONSTA X','')
artist_na('ROCKET PUNCH','')
artist_na('Rocket Punch','ROCKET PUNCH')
artist_na('브이에이브이','VAV')
artist_na('PRISTIN','')
artist_na('SG WANNA BE','')
artist_na('니엘','')
artist_na('구구단','')
artist_na('GUGUDAN','구구단')
artist_na('Block B','')
artist_na('블락비','Block B')
artist_na('BLOCK B','Block B')
artist_na('KNK','')
artist_na('SONAMOO','')
artist_na('HENRY','')
artist_na('MAMAMOO','')
artist_na('Mamamoo','MAMAMOO')
artist_na('MOON BYUL','MAMAMOO')
artist_na('\(G\)i-dle','\(G\)I-DLE')
artist_na('\(G\)-IDLE','\(G\)I-DLE')
artist_na('\(G\)I-DLE','')
artist_na('idle','\(G\)I-DLE')
artist_na('\)아이들','\(G\)I-DLE')
artist_na('I-Dle','\(G\)I-DLE')
artist_na('DRIPPIN','')
artist_na('Drippin','DRIPPIN')
artist_na('LUCY','')
artist_na('ONEWE','')
artist_na('BTS','')
artist_na('GFRIEND','')
artist_na('G FRIEND','GFRIEND')
artist_na('Gfriend','GFRIEND')
artist_na('FORESTELLA','')
artist_na('Forestella','FORESTELLA')
artist_na('PINK FANTASY','')
artist_na('DEF.','DEF.DIVA')
artist_na('HIGHLIGHT','하이라이트')
artist_na('Highlight','하이라이트')
artist_na('하이라이트','')
artist_na('YUN DDAN DDAN','윤딴딴')
artist_na('JANE POP','')
artist_na('9001','')
artist_na('JIAE','')
artist_na('TFN','')
artist_na('SUNWOOJUNGA','')
artist_na('ARO','')
artist_na('ALICE','')
artist_na('HWAJA','')
artist_na('SURL','')
artist_na('SON HYEEUN','')
artist_na('CLASS:y','')
artist_na('NOEL','')
artist_na('ROY KIM','')
artist_na('J.UNA','')
artist_na('Sunmo Yang','')
artist_na('SAAY','')
artist_na('KIHYUN','')
artist_na('WEi','WEI')
artist_na('WEI','')
artist_na('DKZ','')
artist_na('DONGKIZ','DKZ')
artist_na('PATTERN','')
artist_na('Rie','')
artist_na('OMEGA X','')
artist_na('LE SSERAFIM','')
artist_na('AKMU','')
artist_na('STRAY KIDS','')
artist_na('Stray Kids','STRAY KIDS')
artist_na('Stray kids','STRAY KIDS')
artist_na('KWON EUN BI','권은비')
artist_na('KWON EUNBI','권은비')
artist_na('권은비','')
artist_na('KIM YONG JUN','')
artist_na('PARK JI HOON','박지훈')
artist_na('Park Jihoon','박지훈')
artist_na('PARK JIHOON','박지훈')
artist_na('박지훈','')
artist_na('NATURE','')
artist_na('LEE CHAEYEON','')
artist_na('BAEKHO','')
artist_na('UP10TION','')
artist_na('Up10tion','UP10TION')
artist_na('YOOA','')
artist_na('Yooa','YOOA')
artist_na('유아','YOOA')
artist_na('CHEN','')
artist_na('VICTON','')
artist_na('Victon','VICTON')
artist_na('B.I','')
artist_na('AIMERS','')
artist_na('BIBI','')
artist_na('BOA','')
artist_na('BoA','BOA')
artist_na('CSR','')
artist_na('SECRET NUMBER','')
artist_na('pH-1','')
artist_na('KANG DANIEL','')
artist_na('Kang Daniel','KANG DANIEL')
artist_na('KARA','')
artist_na('Ateez','ATEEZ')
artist_na('ATEEZ','')
artist_na('ITZY','')
artist_na('NCT DREAM','')
artist_na('NCT Dream','NCT DREAM')
artist_na('TXT','')
artist_na('AESPA','')
artist_na('aespa','AESPA')
artist_na('에스파','AESPA')
artist_na('WAYV','')
artist_na('WayV','WAYV')
artist_na('WAY V','WAYV')
artist_na('GOT7','')
artist_na('Twice','TWICE')
artist_na('TWICE','')
artist_na('NMIXX','')
artist_na('JOY','')
artist_na('Park Jin Young','')
artist_na('TAEYEON','')
artist_na('TAE YEON','TAEYEON')
artist_na('Taeyeon','TAEYEON')
artist_na('YOUNGJOO SONG','')
artist_na('ONLYONEOF','')
artist_na('온리원오브','ONLYONEOF')
artist_na('NCT','')
artist_na('STAYC','')
artist_na("GIRLS' GENERATION",'GIRLS GENERATION')
artist_na("GENERATION",'GIRLS GENERATION')
artist_na("Girls' Generation",'GIRLS GENERATION')
artist_na('소녀시대','GIRLS GENERATION')
artist_na('Generation','GIRLS GENERATION')
artist_na('GIRLS GENERATION','')
artist_na('NEWJEANS','')
artist_na('뉴진스','NEWJEANS')
artist_na('ENHYPEN','')
artist_na('엔하이픈','ENHYPEN')
artist_na('Enhypen','ENHYPEN')
artist_na('Dreamcatcher','DREAMCATCHER')
artist_na('DREAM CATCHER','DREAMCATCHER')
artist_na('DREAMCATCHER','')
artist_na('SEULGI','')
artist_na('ONEUS','')
artist_na('Oneus','ONEUS')
artist_na('Billlie','BILLLIE')
artist_na('BILLLIE','')
artist_na('IVE','')
artist_na('LISA','')
artist_na('EXID','')
artist_na('LOONA','')
artist_na('PURPLE KISS','')
artist_na('THE BOYZ','')
artist_na('The Boyz','THE BOYZ')
artist_na('HWA SA','')
artist_na('LEE HI','')
artist_na('IU','')
artist_na('KAI','')
artist_na('TNX','')
artist_na('ONEW','')
artist_na('EPIK HIGH','')
artist_na('SUNMI','')
artist_na('Drama OST','OST')
artist_na('TREASURE','')
artist_na('Treasure','TREASURE')
artist_na('Jo YuRi','')
artist_na('JEON SOMI','')
artist_na('HyunA','현아')
artist_na('현아','')
artist_na('HEIZE','')
artist_na('Heize','HEIZE')
artist_na('Brave Girls','')
artist_na('BRAVE GIRLS','')
artist_na('Brave Girls','BRAVE GIRLS')
artist_na('ILY:1','')
artist_na('2PM','')
artist_na('T-ARA','')
artist_na('Weeekly','WEEEKLY')
artist_na('WEEEKLY','')
artist_na('TAN','')
artist_na('D.O','')
artist_na('SUHO','')
artist_na('VIVIZ','')
artist_na('SMTOWN','')
artist_na('SOLAR','')
artist_na('KIM SUNG KYU','')
artist_na('BTOB','')
artist_na('BtoB','BTOB')
artist_na('비투비','BTOB')
artist_na('MIN HYUK','이민혁')
artist_na('MINHYUK','이민혁')
artist_na('이민혁','')
artist_na('Oh My Girl','OH MY GIRL')
artist_na('OH MY GIRL','')
artist_na('PSY','')
artist_na('PENTAGON','')
artist_na('Pentagon','PENTAGON')
artist_na('Apink','APINK')
artist_na('APINK','')
artist_na('에이핑크','APINK')
artist_na("F\(X\)",'에프엑스')
artist_na("f\(x\)",'에프엑스')
artist_na("F\(x\)",'에프엑스')
artist_na("f\(X\)",'에프엑스')
artist_na('에프엑스','')
artist_na('ERIC NAM','')
artist_na('ELRIS','')
artist_na('CRAVITY','')
artist_na('Cravity','CRAVITY')
artist_na('Nu`est','')
artist_na('Nu\'est','Nu`est')
artist_na('뉴이스트','Nu`est')
artist_na('JBJ','')
artist_na('KANG HYEWON','강혜원')
artist_na('KANG HYE WON','')
artist_na('ERIC NAM','강혜원')
artist_na('S.I.S','')
artist_na('LABOUM','')
artist_na('APRIL','')
artist_na('AOA','')
artist_na('CLC','')
artist_na('BOYFRIEND','')
artist_na('Whee In','WHEE IN')
artist_na('WHEE IN','')
artist_na('JEONG SEWOON','정세운')
artist_na('JEONG SE WOON','정세운')
artist_na('A.C.E','')
artist_na('정세운','')
artist_na('TEEN TOP','')
artist_na('Teen Top','TEEN TOP')
artist_na('HOTSHOT','')
artist_na('YERIN','백예린')
artist_na('YE RIN','백예린')
artist_na('백예린','')
artist_na('2NE1','')
artist_na('I.O.I','')
artist_na('IZ*ONE','')
artist_na('아이즈원','IZ*ONE')
artist_na('IZ\*ONE','IZ*ONE')
artist_na('WINNER','')
artist_na('Winner','WINNER')
artist_na('볼빨간사춘기','')
artist_na('볼빨간 사춘기','볼빨간사춘기')
artist_na('BOLBBALGAN4','볼빨간사춘기')
artist_na('KARD','')
artist_na('DKB','')
artist_na('iKON','IKON')
artist_na('Ikon','IKON')
artist_na('IKON','')
artist_na('핑클','')
artist_na('NINE MUSES','')
artist_na('GAIN','')
artist_na('SUPER M','')
artist_na('SUPERM','SUPER M')
artist_na('SuperM','SUPER M')
artist_na('SupreM','SUPER M')
artist_na('VIXX','')
artist_na('INFINITE','')
artist_na('2AM','')
artist_na('PARK HYOSHIN','박효신')
artist_na('PARK HYO SHIN','박효신')
artist_na('박효신','')
artist_na('X1','')
artist_na('엑스원','X1')
artist_na('BT21','BTS')
artist_na('WANNA ONE','')
artist_na('WANNAONE','WANNA ONE')
artist_na('Wanna One','WANNA ONE')
artist_na('WANNA-ONE','WANNA ONE')
artist_na('B.A.P','')
artist_na('CNBLUE','')
artist_na('BAEK HYUN','')
artist_na('BAEKHYUN','BAEK HYUN')
artist_na('크레용팝','')
artist_na('WONDER GIRLS','')
artist_na('버즈','')
artist_na('Buzz','버즈')
artist_na('4MINUTE','포미닛')
artist_na('포미닛','')
artist_na('SISTAR','')
artist_na('걸스데이','')
artist_na('비스트','BEAST')
artist_na('Beast','BEAST')
artist_na('BEAST','')
artist_na('JYJ','')
artist_na('JEON SOYEON','')
artist_na('JEON SO YEON','JEON SOYEON')
artist_na('JIMIN','')
artist_na('CRUSH','')
artist_na('ZICO','')
artist_na('지코','ZICO')
artist_na('WENDY','')
artist_na('웬디','WENDY')
artist_na('이달의 소녀','')
artist_na('Jin','')
artist_na('PARK BO GUM','박보검')
artist_na('PARK BOGUM','박보검')
artist_na('박보검','')
artist_na('OST','')
artist_na('O.S.T','OST')
artist_na('KEY','')
artist_na('PARK KYUNG','')
artist_na('키','KEY')
artist_na('MBLAQ','엠블랙')
artist_na('엠블랙','')
artist_na('미래소년','')
artist_na('RAIN','')
artist_na('비','RAIN')
artist_na('태민','')
artist_na('TAEMIN','태민')
artist_na('TAE MIN','태민')
artist_na('BLACKSWAN','')

/usr/local/lib/python3.8/dist-packages/pandas/core/indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [ ]:
def presale_na(df):
    index1 = df[df['item'].str.contains('Pre') == True].index
    index2 = df[df['item'].str.contains('PRE') == True].index
    index3 = df[df['item'].str.contains('PRe') == True].index
    index4 = df[df['item'].str.contains('pre') == True].index
    index5 = df[df['item'].str.contains('사전') == True].index
    index6 = df[df['item'].str.contains('예약') == True].index
    index7 = df[df['item'].str.contains('Order') == True].index
    index8 = df[df['item'].str.contains('order') == True].index
    index9 = df[df['item'].str.contains('ORDER') == True].index

    df.iloc[index1,-1] = True
    df.iloc[index2,-1] = True
    df.iloc[index3,-1] = True
    df.iloc[index4,-1] = True
    df.iloc[index5,-1] = True
    df.iloc[index6,-1] = True
    df.iloc[index7,-1] = True
    df.iloc[index8,-1] = True
    df.iloc[index9,-1] = True

    return df
presale_na(df)

,item,url,artist,discount_price,price,is_sold_out,ds,vendor,is_autograph,avg_review_value,number_of_questions,number_of_reviews,presale
0,TWICE 11th MINI ALBUM BETWEEN 1&2,https://en.thejypshop.com/product/twice-11th-m...,TWICE,18.55,22.90,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
1,1st Mini Album IM NAYEON,https://en.thejypshop.com/product/1st-mini-alb...,NAYEON,17.82,22.00,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
2,TWICE 1st Mini Album The Story Begins,https://en.thejypshop.com/product/twice-1st-mi...,TWICE,11.91,14.70,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
3,TWICE 3rd Mini Album TWICEcoaster : LANE 1,https://en.thejypshop.com/product/twice-3rd-mi...,TWICE,12.64,15.60,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
4,Special Album TWICEcoaster : LANE 2,https://en.thejypshop.com/product/special-albu...,TWICE,14.09,17.40,False,2022-11-14,jypshop,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22213,"TETEMPEST - 1st Mini Album [It’s ME, It’s WE]",https://shop.mwave.me/en/565732.html,TEMPEST,NaN,28.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22214,P1Harmony - 3rd Mini Album [DISHARMONY : FIND ...,https://shop.mwave.me/en/565642.html,P1Harmony,NaN,26.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22215,fromis_9 – 4th Mini Album [Midnight Guest],https://shop.mwave.me/en/565599.html,Fromis_9,NaN,27.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22216,BLITZERS - 1st Single [BOBBIN],https://shop.mwave.me/en/565506001.html,BLITZERS,NaN,22.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN
22217,KIM JAEHWAN - 4th Mini Album [THE LETTER],https://shop.mwave.me/en/565465001.html,김재환,NaN,28.99,NaN,2022-11-14,mwave,True,NaN,NaN,NaN,NaN

In [ ]:
df['presale'].value_counts()

False    9739
True      604
Name: presale, dtype: int64

In [ ]:
index = df[(df['item'].str.contains('event') == True)|(df['item'].str.contains('EVENT') == True)|(df['item'].str.contains('Event') == True)|(df['item'].str.contains('VIDEO CALL') == True)|(df['item'].str.contains('FAN SIGN') == True)].index
index2 = df.index.drop(index)
 
event = []
  
for i in df.index :
  if i in index :
    event.append(True)

  elif i in index2 :
    event.append(False)

  else :
    event.append(False)

# list(리스트)로부터 'grades'열을 추가합니다.
df['is_event'] = event

df['is_event'].value_counts()

<ipython-input-13-a267ef60cc67>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['is_event'] = event

False    21890
True       328
Name: is_event, dtype: int64

In [ ]:
index = df[(df['item'].str.contains('LIGHT STICK') == True)|(df['item'].str.contains('Light Stick') == True)|(df['item'].str.contains('LIGHT') == True)|(df['item'].str.contains('Light') == True)|
            (df['item'].str.contains('light stick') == True)|(df['item'].str.contains('Stick') == True)|(df['item'].str.contains('STICK') == True)].index

index2 = df[(df['item'].str.contains('ALBUM') == True)|(df['item'].str.contains('Album') == True)|(df['item'].str.contains('미니') == True)|(df['item'].str.contains('Single') == True)|(df['item'].str.contains('Mini') == True)|(df['item'].str.contains('album') == True)|(df['item'].str.contains('MINI') == True)| (df['item'].str.contains('앨범') == True)|(df['item'].str.contains('정규')== True)|(df['item'].str.contains('싱글') == True)|(df['item'].str.contains('Photobook') == True)].index

index3 = df[(df['item'].str.contains('SEASON') == True)|(df['item'].str.contains('GREETING') == True)|(df['item'].str.contains('SUMMER') == True)|(df['item'].str.contains('WINTER') == True)|
            (df['item'].str.contains('Season') == True)|(df['item'].str.contains('SEASON’S GREETINGS') == True)|(df['item'].str.contains('CALENDAR') == True)|(df['item'].str.contains('DVD') == True)].index            

index4 = df[(df['item'].str.contains('BADGE') == True)|(df['item'].str.contains('Badge') == True)|(df['item'].str.contains('Keyring') == True)|(df['item'].str.contains('Button') == True)|
            (df['item'].str.contains('badge') == True)|(df['item'].str.contains('KEYCHAIN') == True)|(df['item'].str.contains('KEYRING') == True)].index

category = []

for i in df.index :
    if i in index :
        category.append('LIGHT STICK')

    elif i in index2 :
        category.append('ALBUM')

    elif i in index3:
        category.append('SEASON’S GREETINGS')

    elif i in index4:
        category.append('Badge & Keyring')

    else :
        category.append('ect')

# list(리스트)로부터 'grades'열을 추가합니다.
df['category'] = category

<ipython-input-14-7c3ac2abc8f5>:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['category'] = category

In [ ]:
df['category'].value_counts()

ALBUM                 15654
ect                    4384
SEASON’S GREETINGS     1030
LIGHT STICK             839
Badge & Keyring         311
Name: category, dtype: int64

In [ ]:
drop_index = df[df['is_sold_out'].isna() == True].index

In [ ]:
df.drop(drop_index,inplace = True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [ ]:
df.isna().sum()

item                       0
url                        0
artist                  3371
discount_price         17135
price                      0
is_sold_out                0
ds                         0
vendor                     0
is_autograph           10016
avg_review_value       11512
number_of_questions    11512
number_of_reviews      11512
presale                11836
is_event                   0
category                   0
dtype: int64

In [ ]:
df['is_sold_out'].isna().sum()

0

In [ ]:
import datetime as dt
df['ds'] = df['ds'].astype('datetime64')
df['year'] = df['ds'].dt.year
df['month'] = df['ds'].dt.month

<ipython-input-20-b32e11b45612>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ds'] = df['ds'].astype('datetime64')
<ipython-input-20-b32e11b45612>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['year'] = df['ds'].dt.year
<ipython-input-20-b32e11b45612>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['month'] = df['ds'].dt.month

In [ ]:
!pip install category_encoders 
!pip install eli5 
!pip install pdpbox

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from category_encoders import OrdinalEncoder
from sklearn.ensemble import RandomForestClassifier

from pdpbox.pdp import pdp_isolate, pdp_plot

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: category_encoders in /usr/local/lib/python3.8/dist-packages (2.6.0)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.0.2)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.3.5)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.21.6)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (0.12.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.8/dist-packages (from category_encoders) (1.7.3)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.5->category_encoders) (2022.7.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from patsy>=0.5.1->category_encoders) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.1.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.2.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: eli5 in /usr/local/lib/python3.8/dist-packages (0.13.0)
Requirement already satisfied: graphviz in /usr/local/lib/python3.8/dist-packages (from eli5) (0.10.1)
Requirement already satisfied: attrs>17.1.0 in /usr/local/lib/python3.8/dist-packages (from eli5) (22.2.0)
Requirement already satisfied: tabulate>=0.7.7 in /usr/local/lib/python3.8/dist-packages (from eli5) (0.8.10)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from eli5) (1.7.3)
Requirement already satisfied: six in /usr/local/lib/python3.8/dist-packages (from eli5) (1.15.0)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from eli5) (3.1.2)
Requirement already satisfied: scikit-learn>=0.20 in /usr/local/lib/python3.8/dist-packages (from eli5) (1.0.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from eli5) (1.21.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2>=3.0.0->eli5) (2.0.1)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20->eli5) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from scikit-learn>=0.20->eli5) (3.1.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pdpbox
  Using cached PDPbox-0.2.1.tar.gz (34.0 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.8/dist-packages (from pdpbox) (1.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from pdpbox) (1.21.6)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/dist-packages (from pdpbox) (1.7.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from pdpbox) (1.2.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.8/dist-packages (from pdpbox) (5.4.8)
Collecting matplotlib==3.1.1
  Using cached matplotlib-3.1.1.tar.gz (37.8 MB)
  Preparing metadata (setup.py) ... done
Collecting sklearn
  Using cached sklearn-0.0.post1.tar.gz (3.6 kB)
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

ModuleNotFoundError: ignored

In [ ]:
train, test = train_test_split(df)

target = 'is_sold_out'
features = ['artist', 'discount_price', 'price',
       'vendor', 'is_autograph', 'avg_review_value',
       'number_of_reviews', 'presale', 'is_event', 'category']

X_train, y_train = train[features], train[target]
X_test, y_test = test[features], test[target]

In [ ]:
y_train = y_train.replace([True,False],['1','0']).astype('int')
y_test = y_test.replace([True,False],['1','0']).astype('int')

In [ ]:
# 기준모델
from sklearn.metrics import accuracy_score

base = y_train.mode()[0]
baseline = len(y_train) * [base]
baseline_acc = accuracy_score(y_train, baseline)
print(f'기준모델의 정확도는 {baseline_acc.round(3)} 입니다')

기준모델의 정확도는 0.743 입니다

In [ ]:
X_train

,artist,discount_price,price,vendor,is_autograph,avg_review_value,number_of_reviews,presale,is_event,category
7148,WONDER GIRLS,NaN,19.99,musicplaza,False,5.0,4.0,NaN,False,ALBUM
4369,Yoon Jisung,13.24,15.58,kpopalbums,False,NaN,NaN,NaN,False,ALBUM
16347,NaN,NaN,23.99,kpopstoreinusa,NaN,NaN,NaN,False,False,ALBUM
13189,APRIL,NaN,59.99,kpopstoreinusa,NaN,NaN,NaN,False,False,ALBUM
5047,NaN,NaN,25.99,musicplaza,False,5.0,1.0,NaN,False,ALBUM
...,...,...,...,...,...,...,...,...,...,...
605,ITZY,11.97,13.30,kpopalbums,False,5.0,2.0,NaN,False,ALBUM
17751,IVE,NaN,23.99,kpopstoreinusa,NaN,NaN,NaN,False,False,ALBUM
8147,DAY6,NaN,49.99,musicplaza,False,5.0,3.0,NaN,False,LIGHT STICK
14691,WAYV,NaN,41.99,kpopstoreinusa,NaN,NaN,NaN,False,False,ect
11814,INFINITE,NaN,5.99,musicplaza,False,0.0,0.0,NaN,False,ALBUM

In [ ]:
encoder = OrdinalEncoder()
X_train_encoded = encoder.fit_transform(X_train)
X_test_encoded = encoder.transform(X_test)

imputer = SimpleImputer(strategy = "most_frequent")
X_train_imput = imputer.fit_transform(X_train_encoded)
X_test_imput = imputer.transform(X_test_encoded)

In [ ]:
from imblearn.over_sampling import SMOTE

# 검증 데이터나 테스트 데이터가 아닌 학습데이터에서만 오버샘플링 사용할 것
smote = SMOTE(random_state=42)
X_train_over, y_train_over = smote.fit_resample(X_train_imput, y_train)

In [ ]:
from category_encoders import OrdinalEncoder
from sklearn.impute import SimpleImputer
from xgboost import XGBClassifier
from sklearn.pipeline import make_pipeline
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, \
  accuracy_score, plot_confusion_matrix, confusion_matrix, classification_report, recall_score, \
  precision_score, f1_score, roc_auc_score, roc_curve


sp_weight = y_train.value_counts()[0] / y_train.value_counts()[1]

pipe = make_pipeline(
    OrdinalEncoder(),
    SimpleImputer(strategy = "most_frequent"),
    XGBClassifier(
        objective="binary:logistic",
        n_jobs=-1,
        eval_metric= "error",
        random_state=42,
        n_estimators= 100,
        max_depth=14,
        colsample_bytree = 1.0,
        learning_rate = 1.0,
        min_child_weight =1
    ),
)

pipe.fit(X_train_over, y_train_over)

Warning: No categorical columns found. Calling 'transform' will only return input data.

Pipeline(steps=[('ordinalencoder', OrdinalEncoder(cols=[], mapping=[])),
                ('simpleimputer', SimpleImputer(strategy='most_frequent')),
                ('xgbclassifier',
                 XGBClassifier(colsample_bytree=1.0, eval_metric='error',
                               learning_rate=1.0, max_depth=14, n_jobs=-1,
                               random_state=42))])

In [ ]:
model = XGBClassifier(
        objective="binary:logistic",
        n_jobs=-1,
        eval_metric= "error",
        random_state=42,
        max_depth=14,
        colsample_bytree = 1.0,
        learning_rate = 1.0,
        min_child_weight =1
    )
watchlist = [(X_train_over, y_train_over), (X_test_imput, y_test)]

#model.fit(
    X_train_over,
    y_train_over,
    eval_set=watchlist,
    early_stopping_rounds=50,  # 50 rounds 동안 성능 개선이 없으면 학습을 중지합니다.
)

IndentationError: ignored

In [ ]:
params = {
    "xgbclassifier__max_depth": [5,14],
    "xgbclassifier__min_child_weight": [1],
    "xgbclassifier__colsample_bytree": [1.0],
    "xgbclassifier__learning_rate": [0.9,1.0]
}

In [ ]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(pipe, param_grid=params, scoring="f1", cv=5, verbose=3)
grid_search.fit(X_train_over, y_train_over)

In [ ]:
print("최적 하이퍼파라미터: ", grid_search.best_params_)
print("최적 f1 score: ", grid_search.best_score_)

In [ ]:
train_xg = classification_report(y_train, pipe.predict(X_train_imput), output_dict=True)
test_xg = classification_report(y_test, pipe.predict(X_test_imput), output_dict=True)

print(f'훈련 정확도  : {train_xg["accuracy"]:.4f}')
print(f'검증 정확도  : {test_xg["accuracy"]:.4f}')
print(f'훈련 f1      : {train_xg["1"]["f1-score"]:.4f}')
print(f'검증 f1      : {test_xg["1"]["f1-score"]:.4f}')

In [ ]:
import matplotlib.pyplot as plt

feature_importances = list(
    zip(X_train.columns, pipe.named_steps["xgbclassifier"].feature_importances_)
)
feature_importances = sorted(feature_importances, key=lambda x: x[1], reverse=True)

plt.figure(figsize=(10, 10), dpi=120)
plt.barh(*list(zip(*feature_importances[::-1])))
plt.axvline(0.015, color="red", linewidth=0.5)

In [ ]:
df.to_csv('데이터 전처리.csv')